Change workflow

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -30,7 +30,45 @@ jobs:
           S6_VERSIONS=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases | jq -r '.[].tag_name' | grep -vE "rc|alpha" | sort -V | tail -n 3 | tac | sed 's/v//g' | jq -Rcn '[inputs]')
           echo "s6-versions=${S6_VERSIONS}" >> "$GITHUB_OUTPUT"
 
-  build:
+  test:
+    needs: setup
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        alpine-version: ${{ fromJson(needs.setup.outputs.alpine-versions) }}
+        s6-version: ${{ fromJson(needs.setup.outputs.s6-versions) }}
+    steps:
+    - 
+      uses: actions/checkout@v2
+    
+    - 
+      name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
+    
+    -
+      name: Build for Test
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        load: true
+        tags: |
+          local/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
+        build-args: | 
+          ALPINE_VERSION=${{ matrix.alpine-version }}
+          S6_OVERLAY_VERSION=${{ matrix.s6-version }}
+    -
+      name: Test
+      run: |
+        output=$(docker run --rm local/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ matrix.alpine-version }} && echo 'OK' || echo 'KO'")
+          if [ "$output" == "OK" ]; then
+            echo "Test Passed"
+          else
+            echo "Test Failed"
+            exit 1
+          fi
+  
+  publish:
     needs: setup
     runs-on: ubuntu-latest
     strategy:
@@ -57,45 +95,12 @@ jobs:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GIT_HUB_TOKEN }}
-    -
-      name: Debug
-      run: |
-        echo "alpine-version=${{ matrix.alpine-version }}"
-        echo "s6-version=${{ matrix.s6-version }}"
-        echo "latest=${{ (matrix.alpine-version == fromJson(needs.setup.outputs.alpine-versions)[0] && matrix.s6-version == fromJson(needs.setup.outputs.s6-versions)[0]) && 'tundrasoft/alpine2:latest, ghcr.io/tundrasoft/alpine2:latest' }}"
-    - name: Build for Test
+
+    - name: Push
       uses: docker/build-push-action@v2
       with:
         context: .
-        load: true
-        tags: |
-          tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
-          ghcr.io/tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
-          ${{ (matrix.alpine-version == fromJson(needs.setup.outputs.alpine-versions)[0] && matrix.s6-version == fromJson(needs.setup.outputs.s6-versions)[0]) && 'tundrasoft/alpine2:latest, ghcr.io/tundrasoft/alpine2:latest' }}
-        build-args: | 
-          ALPINE_VERSION=${{ matrix.alpine-version }}
-          S6_OVERLAY_VERSION=${{ matrix.s6-version }}
-
-    - name: Test
-      run: |
-        output=$(docker run --rm tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ matrix.alpine-version }} && echo 'OK' || echo 'KO'")
-          if [ "$output" == "OK" ]; then
-            echo "Test Passed"
-          else
-            echo "Test Failed"
-            exit 1
-          fi
-    # - 
-    #   name: Push
-    #   run: |
-    #     docker push tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
-    #     docker push ghcr.io/tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
-    #     ${{ (matrix.alpine-version == fromJson(needs.setup.outputs.alpine-versions)[0] && matrix.s6-version == fromJson(needs.setup.outputs.s6-versions)[0]) && 'docker push tundrasoft/alpine2:latest && docker push ghcr.io/tundrasoft/alpine2:latest' }}
-
-    - name: Build for Test
-      uses: docker/build-push-action@v2
-      with:
-        context: .
+        platforms: linux/amd64,linux/arm/v8,linux/arm/v7
         push: true
         tags: |
           tundrasoft/alpine2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
