Enable building and testing

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -95,27 +95,27 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GIT_HUB_TOKEN }}
       
-      # -
-      #   name: Build and test
-      #   id: docker_build
-      #   uses: docker/build-push-action@v5
-      #   with:
-      #     context: .
-      #     build-args: |
-      #       ALPINE_VERSION=${{ matrix.alpine-version }}
-      #       S6_OVERLAY_VERSION=${{ matrix.s6-version }}
-      #     load: true
-      #     tags: alpine-test-${{ matrix.alpine-version }}-${{ matrix.s6-version }}
-      # -
-      #   name: Test
-      #   run: |
-      #     output=$(docker run --rm alpine-test-${{ matrix.alpine-version }}-${{ matrix.s6-version }} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ matrix.alpine-version }} && echo 'OK' || echo 'KO'")
-      #     if [ "$output" == "OK" ]; then
-      #       echo "Test Passed"
-      #     else
-      #       echo "Test Failed"
-      #       exit 1
-      #     fi
+      -
+        name: Build and test
+        id: docker_build
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          build-args: |
+            ALPINE_VERSION=${{ matrix.alpine-version }}
+            S6_OVERLAY_VERSION=${{ matrix.s6-version }}
+          load: true
+          tags: alpine-test-${{ matrix.alpine-version }}-${{ matrix.s6-version }}
+      -
+        name: Test
+        run: |
+          output=$(docker run --rm alpine-test-${{ matrix.alpine-version }}-${{ matrix.s6-version }} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ matrix.alpine-version }} && echo 'OK' || echo 'KO'")
+          if [ "$output" == "OK" ]; then
+            echo "Test Passed"
+          else
+            echo "Test Failed"
+            exit 1
+          fi
       -
         name: Build & Push
         if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
